services:
  rails:
    build: .
    volumes:
      - .:/workspace
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    command: sleep infinity

volumes:
  bundle:
